### PR TITLE
Log the Vips error buffer when VipsException are thrown

### PR DESCRIPTION
**Pull request by anthonyroussel**
Hello

I needed to test and debug some C code in the JVips project.

To better diagnose the errors that can be encountered with libvips, it is possible to retrieve the contents of the Vips error buffer with : https://github.com/libvips/libvips/blob/master/libvips/iofuncs/error.c#L178

This buffer contains possible explanations of why a libvips call might have failed, and it helped me a lot during my tests.

That's why I propose this PR to log the content of the Vips error buffer when a VipsException is thrown from the C code :)

Anthony

### CODE REVIEW

**Review by dbouron — APPROVED** [review]

**Review by dbouron — APPROVED** [review]

**Review by dbouron — APPROVED** [review]
Thanks for updating the Readme :)

**Review by dbouron — COMMENTED** [review]
Looks good to me, but the Windows build failed. There is undefined references with vips_error_clear and vips_error_buffer

**Review by dbouron — CHANGES_REQUESTED** [review]
It seems that in the test, on Windows platform, libvips is not linked properly. I think you should append `"-lvips"` at [this line](https://github.com/criteo/JVips/blob/master/src/test/c/CMakeLists.txt#L5)

**Comment by anthonyroussel** [comment]
Hello Dimitri

Thanks for the review :)

> It seems that in the test, on Windows platform, libvips is not linked properly. I think you should append "-lvips" at this line

Indeed, looks like appending "-lvips" at this line is a resolution for the failing Windows build.
I will update the pull request.

Thanks,
Anthony

**Review by dbouron — APPROVED** [review]
LGTM, thank you for your contribution

**Comment by klh** [comment]
this has removed support for avif

**Pull request merged**
